name: Publish nifi image
# https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
on: [push]

env:
  NIFI_VERSION: '1.25.0'
  BASE_URL: 'https://dlcdn.apache.org'
  IMAGE_NAME: 'public.ecr.aws/docker/library/eclipse-temurin'
  IMAGE_TAG: '21-jre'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download Nifi Release
        run: |
          curl -L https://github.com/apache/nifi/archive/refs/tags/rel/nifi-${{env.NIFI_VERSION}}.tar.gz -o nifi-${{env.NIFI_VERSION}}.tar.gz
          tar -xzf nifi-${{env.NIFI_VERSION}}.tar.gz
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./nifi-rel-nifi-${{env.NIFI_VERSION}}/nifi-docker/dockerhub
          file: ./nifi-rel-nifi-${{env.NIFI_VERSION}}/nifi-docker/dockerhub/Dockerfile
          build-args: |
              IMAGE_NAME=${{env.IMAGE_NAME}}
              IMAGE_TAG=${{env.IMAGE_TAG}}
              BASE_URL=${{env.BASE_URL}}
              NIFI_VERSION=${{env.NIFI_VERSION}}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/nifi-${{env.NIFI_VERSION}}-jre17
