name: Publish nifi image
# https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download Nifi Release
        run: |
          curl -L https://github.com/apache/nifi/archive/refs/tags/rel/nifi-1.23.2.tar.gz -o  nifi-1.23.2.tar.gz
          tar -xzf nifi-1.23.2.tar.gz
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./nifi-rel-nifi-1.23.2/nifi-docker/dockerhub
          file: ./nifi-rel-nifi-1.23.2/nifi-docker/dockerhub/Dockerfile
          build-args: |
              IMAGE_NAME=public.ecr.aws/docker/library/eclipse-temurin
              IMAGE_TAG=17-jre
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/nifi-1.23.2-jre17